version: "3.7"

services:
  properties:
    container_name: escalade-properties
    image: properties-server:latest
    restart: unless-stopped
    environment:
      - jasypt.encryptor.password=${JASYPT_ENCRYPTOR_SECRET}
    ports:
    - "8888:8888"
    networks:
      net:
        ipv4_address: 10.5.0.2


  db:
    container_name: escalade-db
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${ESCALADE_DB_LOGIN}
      POSTGRES_PASSWORD: ${ESCALADE_DB_PASSWORD}
      POSTGRES_DB: escalade
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      net:
        ipv4_address: 10.5.0.5

  api:
    container_name: escalade-api
    image: escalade-api:latest
    restart: on-failure
    build: ./
    environment:
      - jasypt.encryptor.password=${JASYPT_ENCRYPTOR_SECRET}
      - spring.cloud.config.uri=http://10.5.0.2:8888
      - spring.datasource.url=jdbc:postgresql://10.5.0.5:5432/escalade
      #- spring.cloud.config.uri=http://127.0.0.1:8888
      #- spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/escalade
    volumes:
      - //f/images:/images
    depends_on:
      - "properties"
      - "db"
    ports:
      - "9090:9090"
    networks:
      net:
        ipv4_address: 10.5.0.3

volumes:
  pgdata:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

